datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://192.168.99.100:32770/fonbet
  username: postgres
  password:

selenium:
  driver:
    chrome:
      path: /Users/kingreeve/Desktop/OTHER/fonbet/fonbet-observer/chromedriver

path:
  timeline: https://www.fonbet.ru/#!/bets/volleyball
  live: https://www.fonbet.ru/#!/live/volleyball

logging:
  level:
    fonbet.observer: debug