datasource:
  driverClassName: org.postgresql.Driver
  url: url
  username: username
  password: password

selenium:
  driver:
    chrome:
      path: path-to-driver/chromedriver

path:
  timeline: https://www.fonbet.ru/#!/bets/volleyball
  live: https://www.fonbet.ru/#!/live/volleyball

logging:
  level:
    fonbet.observer: debug
